apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: santanarael/payment-fiap
          ports:
            - containerPort: 3001
          env:
            - name: ML_PUBLIC_KEY
              value: TEST-580c0533-1d6b-4cd6-a936-42b0051102df
            - name: ML_ACCESS_TOKEN
              value: TEST-7456580585039188-012819-455f57e3f99cb1ca44c09a1ac2373791-304069289
          resources:
            requests:
              memory: '128Mi' # Mem칩ria inicial / MI = milicores (1 core = 1000 milicores)
              cpu: '100m' # CPU inicial
            limits:
              memory: '628Mi' # Limite m치ximo de mem칩ria
              cpu: '300m' # Limite m치ximo de CPU  / M = megabytes
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 34343
      targetPort: 3002
  type: LoadBalancer